# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency: production

jobs:
  build:

    runs-on: ubuntu-latest

    permissions: write-all

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Build linux-arm64
      run: |
          dotnet restore
          dotnet publish --no-restore --runtime linux-arm64 --self-contained -c Release -o release_linux_arm64
    - name: Build linux-x64
      run: |
          dotnet restore
          dotnet publish --no-restore --runtime linux-x64 --self-contained -c Release -o release_linux_x64
    - name: Build win-x64
      run: |
          dotnet restore
          dotnet publish --no-restore --runtime win-x64 --self-contained -c Release -o release_win_x64
    - name: Create release zips
    - run: zip release-linux-x64.zip release_linux_x64/* -r
    - run: zip release-linux-arm64.zip release_linux_arm64/* -r
    - run: zip release-win-x64.zip release_win_x64/* -r
    - name: Generate release tag
      id: generate_release_tag
      uses: amitsingh-007/next-release-tag@v5.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: 'v'
        tag_template: 'yyyy.mm.dd.i'
    - name: Test
      run: ls -al
    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.generate_release_tag.outputs.next_release_tag }}
        sha: ${{ github.sha }}
      run: |
        gh release create "$tag" \
          --repo="$GITHUB_REPOSITORY" \
          --title="${GITHUB_REPOSITORY#*/} $tag ($sha)" \
          --generate-notes release-linux-x64.zip release-linux-arm64.zip release-win-x64.zip